/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author hp
 */
public class Persegi extends javax.swing.JFrame {
double SISI,KELILING,LUAS;
    /**
     * Creates new form Persegi
     */
    public Persegi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LPERSEGI = new javax.swing.JLabel();
        LSISI = new javax.swing.JLabel();
        TSISI = new javax.swing.JTextField();
        BHITUNG = new javax.swing.JButton();
        BRESET = new javax.swing.JButton();
        BKEMBALI = new javax.swing.JButton();
        LKeliling = new javax.swing.JLabel();
        LLuas = new javax.swing.JLabel();
        TKeliling = new javax.swing.JTextField();
        TLuas = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LPERSEGI.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        LPERSEGI.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LPERSEGI.setText("PERSEGI");

        LSISI.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LSISI.setText("SISI");

        TSISI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TSISIActionPerformed(evt);
            }
        });

        BHITUNG.setText("HITUNG");
        BHITUNG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BHITUNGActionPerformed(evt);
            }
        });

        BRESET.setText("RESET");
        BRESET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BRESETActionPerformed(evt);
            }
        });

        BKEMBALI.setText("KEMBALI");
        BKEMBALI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BKEMBALIActionPerformed(evt);
            }
        });

        LKeliling.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LKeliling.setText("keliling");

        LLuas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LLuas.setText("luas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(LPERSEGI))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LSISI)
                                    .addComponent(BHITUNG)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LKeliling)
                                    .addComponent(LLuas))))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 44, Short.MAX_VALUE)
                                .addComponent(BRESET)
                                .addGap(59, 59, 59)
                                .addComponent(BKEMBALI))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TSISI, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(TLuas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                                        .addComponent(TKeliling, javax.swing.GroupLayout.Alignment.LEADING)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LPERSEGI)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LSISI)
                    .addComponent(TSISI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BHITUNG)
                    .addComponent(BRESET)
                    .addComponent(BKEMBALI))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LKeliling)
                    .addComponent(TKeliling, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LLuas)
                    .addComponent(TLuas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TSISIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TSISIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TSISIActionPerformed

    private void BKEMBALIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BKEMBALIActionPerformed
        // TODO add your handling code here:
         this.setVisible(false);
    }//GEN-LAST:event_BKEMBALIActionPerformed

    private void BHITUNGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BHITUNGActionPerformed
        // TODO add your handling code here:
        double sisi = Double.parseDouble(TSISI.getText());
        double keliling = 4 * sisi;
        TKeliling.setText(String.valueOf(keliling));
        
        // Perhitungan Luas
        double luas = sisi * sisi;
        TLuas.setText(String.valueOf(luas));
    }//GEN-LAST:event_BHITUNGActionPerformed

    private void BRESETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BRESETActionPerformed
        // TODO add your handling code here:
        TSISI.setText("");
        TKeliling.setText("");
        TLuas.setText("");
    }//GEN-LAST:event_BRESETActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Persegi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Persegi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Persegi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Persegi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Persegi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BHITUNG;
    private javax.swing.JButton BKEMBALI;
    private javax.swing.JButton BRESET;
    private javax.swing.JLabel LKeliling;
    private javax.swing.JLabel LLuas;
    private javax.swing.JLabel LPERSEGI;
    private javax.swing.JLabel LSISI;
    private javax.swing.JTextField TKeliling;
    private javax.swing.JTextField TLuas;
    private javax.swing.JTextField TSISI;
    // End of variables declaration//GEN-END:variables
}
