/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author hp
 */
public class PersegiPanjang extends javax.swing.JFrame {
    double PANJANG,LEBAR,LUAS,KELILING;

    /**
     * Creates new form PersegiPanjang
     */
    public PersegiPanjang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LPERSEGIPANJANG = new javax.swing.JLabel();
        LabelPANJANG = new javax.swing.JLabel();
        LabelLEBAR = new javax.swing.JLabel();
        TMasukanPanjang = new javax.swing.JTextField();
        TMasukanLebar = new javax.swing.JTextField();
        BHITUNG = new javax.swing.JButton();
        BRESET = new javax.swing.JButton();
        BKEMBALI = new javax.swing.JButton();
        LabelLUAS = new javax.swing.JLabel();
        LabelKELILING = new javax.swing.JLabel();
        TLuas = new javax.swing.JTextField();
        TKeliling = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LPERSEGIPANJANG.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        LPERSEGIPANJANG.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LPERSEGIPANJANG.setText("PERSEGIPANJANG");

        LabelPANJANG.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelPANJANG.setText("PANJANG");

        LabelLEBAR.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelLEBAR.setText("LEBAR");

        TMasukanPanjang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TMasukanPanjangActionPerformed(evt);
            }
        });

        BHITUNG.setText("HITUNG");
        BHITUNG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BHITUNGActionPerformed(evt);
            }
        });

        BRESET.setText("RESET");
        BRESET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BRESETActionPerformed(evt);
            }
        });

        BKEMBALI.setText("KEMBALI");
        BKEMBALI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BKEMBALIActionPerformed(evt);
            }
        });

        LabelLUAS.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelLUAS.setText("LUAS");

        LabelKELILING.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelKELILING.setText("KELILING");

        TKeliling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TKelilingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BHITUNG)
                    .addComponent(LabelPANJANG, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LabelLEBAR, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LabelLUAS, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LabelKELILING, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BRESET)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BKEMBALI))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TKeliling, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TLuas, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TMasukanLebar)
                            .addComponent(LPERSEGIPANJANG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TMasukanPanjang))
                        .addGap(116, 116, 116))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(LPERSEGIPANJANG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelPANJANG)
                    .addComponent(TMasukanPanjang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelLEBAR)
                    .addComponent(TMasukanLebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BHITUNG)
                    .addComponent(BRESET)
                    .addComponent(BKEMBALI))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TLuas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelLUAS))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TKeliling, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelKELILING))
                .addGap(0, 66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TMasukanPanjangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TMasukanPanjangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TMasukanPanjangActionPerformed

    private void TKelilingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TKelilingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TKelilingActionPerformed

    private void BHITUNGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BHITUNGActionPerformed
        // TODO add your handling code here:
        double PANJANG = Double.parseDouble(TMasukanPanjang.getText());
        double LEBAR = Double.parseDouble(TMasukanLebar.getText());
        
        double LUAS = PANJANG * LEBAR;
        double KELILING = 2 * (PANJANG + LEBAR);

        TLuas.setText(String.valueOf(LUAS));
        TKeliling.setText(String.valueOf(KELILING));
    }//GEN-LAST:event_BHITUNGActionPerformed

    private void BRESETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BRESETActionPerformed
        // TODO add your handling code here:
        LabelPANJANG.setText("");
        LabelLEBAR.setText("");
        TLuas.setText("");
        TKeliling.setText("");
    }//GEN-LAST:event_BRESETActionPerformed

    private void BKEMBALIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BKEMBALIActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_BKEMBALIActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PersegiPanjang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PersegiPanjang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PersegiPanjang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PersegiPanjang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PersegiPanjang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BHITUNG;
    private javax.swing.JButton BKEMBALI;
    private javax.swing.JButton BRESET;
    private javax.swing.JLabel LPERSEGIPANJANG;
    private javax.swing.JLabel LabelKELILING;
    private javax.swing.JLabel LabelLEBAR;
    private javax.swing.JLabel LabelLUAS;
    private javax.swing.JLabel LabelPANJANG;
    private javax.swing.JTextField TKeliling;
    private javax.swing.JTextField TLuas;
    private javax.swing.JTextField TMasukanLebar;
    private javax.swing.JTextField TMasukanPanjang;
    // End of variables declaration//GEN-END:variables

        }
    

