/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author hp
 */
public class Segitiga extends javax.swing.JFrame {
    double SISI,LUAS,KELILING;

    /**
     * Creates new form Segitiga
     */
    public Segitiga() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LSegitiga = new javax.swing.JLabel();
        LSisi = new javax.swing.JLabel();
        TMasukkanSisi = new javax.swing.JTextField();
        BHITUNG = new javax.swing.JButton();
        BRESET = new javax.swing.JButton();
        BKEMBALI = new javax.swing.JButton();
        LLuas = new javax.swing.JLabel();
        LKelilling = new javax.swing.JLabel();
        TLuas = new javax.swing.JTextField();
        LKeliling = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LSegitiga.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        LSegitiga.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LSegitiga.setText("SEGITIGA");

        LSisi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LSisi.setText("SISI");

        TMasukkanSisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TMasukkanSisiActionPerformed(evt);
            }
        });

        BHITUNG.setText("HITUNG");
        BHITUNG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BHITUNGActionPerformed(evt);
            }
        });

        BRESET.setText("RESET");
        BRESET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BRESETActionPerformed(evt);
            }
        });

        BKEMBALI.setText("KEMBALI");
        BKEMBALI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BKEMBALIActionPerformed(evt);
            }
        });

        LLuas.setText("LUAS");

        LKelilling.setText("KELILING");

        LKeliling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LKelilingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LSisi)
                    .addComponent(BHITUNG)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LLuas)
                            .addComponent(LKelilling))))
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(LSegitiga, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LKeliling, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                    .addComponent(TLuas, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TMasukkanSisi)
                    .addComponent(BRESET, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(BKEMBALI)
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(LSegitiga)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LSisi)
                    .addComponent(TMasukkanSisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BHITUNG)
                    .addComponent(BRESET)
                    .addComponent(BKEMBALI))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LLuas)
                    .addComponent(TLuas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LKelilling)
                    .addComponent(LKeliling, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LKelilingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LKelilingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LKelilingActionPerformed

    private void TMasukkanSisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TMasukkanSisiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TMasukkanSisiActionPerformed

    private void BHITUNGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BHITUNGActionPerformed
        // TODO add your handling code here:
        // Mengambil nilai sisi dari input teks
    double sisi = Double.parseDouble(TMasukkanSisi.getText());
    
    // Menghitung tinggi segitiga
    double tinggi = Math.sqrt(Math.pow(sisi, 2) - Math.pow(sisi / 2, 2));
    
    // Menghitung luas segitiga
    double luas = 0.5 * sisi * tinggi;
    
    // Menghitung keliling segitiga
    double keliling = 3 * sisi;
    
    // Menetapkan nilai luas dan keliling ke dalam komponen teks yang sesuai
    TLuas.setText(String.valueOf(luas));
    LKeliling.setText(String.valueOf(keliling));
    }//GEN-LAST:event_BHITUNGActionPerformed

    private void BRESETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BRESETActionPerformed
        // TODO add your handling code here:
        // Reset semua inputan
        TMasukkanSisi.setText("");
        TLuas.setText("");
        LKeliling.setText("");
    }//GEN-LAST:event_BRESETActionPerformed

    private void BKEMBALIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BKEMBALIActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_BKEMBALIActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Segitiga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Segitiga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Segitiga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Segitiga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Segitiga().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BHITUNG;
    private javax.swing.JButton BKEMBALI;
    private javax.swing.JButton BRESET;
    private javax.swing.JTextField LKeliling;
    private javax.swing.JLabel LKelilling;
    private javax.swing.JLabel LLuas;
    private javax.swing.JLabel LSegitiga;
    private javax.swing.JLabel LSisi;
    private javax.swing.JTextField TLuas;
    private javax.swing.JTextField TMasukkanSisi;
    // End of variables declaration//GEN-END:variables
}
